region: us-east-1
zone: us-east-1c
ami_id: ami-046a7ae55d7ca9cee #screeley-ocp311-base3 
machine_type: t2.large
sec_group_id: sg-0cee6560b4bf47f6e #default
subnet_id: subnet-06686f4cf356cc45a #jcope-workspace
tag_name: jcope-demo
